#
# see here for syntax:
# https://clangd.llvm.org/config.html
#
Diagnostics:
  ClangTidy:
    Add: modernize*
    Add: abseil*
    Add: concurrency*
    Add: cppcoreguidelines*
    Add: google*
    Add: performance*
    Add: readability*
    Add: portability*
    Add: bugprone*
    Add: misc*
    Remove: modernize-use-trailing-return-type

CompileFlags: # Tweak the parse settings
  Add:
    - "--include-directory=/home/user/ssunsnjar/src/bdf-toolkit-cpp/tests/googletest/googletest/include"
    - "--include-directory=/home/user/ssunsnjar/src/bdf-toolkit-cpp/tests/googletest/googlemock/include"
