#
# see here for syntax:
# https://clangd.llvm.org/config.html
#
Diagnostics:
  ClangTidy:
    Add:
      - "modernize*"
      - "abseil*"
      - "concurrency*"
      - "cppcoreguidelines*"
      - "google*"
      - "performance*"
      - "readability*"
      - "portability*"
      - "bugprone*"
      - "misc*"
      - "clang-analyzer-*"
      - "cert-*"
      - "clang-*"
      - "hicpp-*"
      - "misra-*"
      - "fds-*"
      - "boost-*"
      - "llvm-*"
      - "fuchsia-*"

    Remove:
      - "modernize-use-trailing-return-type"
      - "fuchsia-default-arguments-calls"
      - "fuchsia-default-arguments-declarations"

CompileFlags: # Tweak the parse settings
  Add:
    - "-std=c++20"

# CompilationDatabase: "path_to_nonstd/compile_commands.json"
